# Generated by Django 5.1.6 on 2025-03-02 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='photo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='photo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.CharField(max_length=255),
        ),
    ]
