# Generated by Django 5.1.6 on 2025-03-02 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0002_alter_business_photo_alter_event_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='photo',
            field=models.ImageField(upload_to='business_photos/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='photo',
            field=models.ImageField(upload_to='event_photos/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(upload_to='product_photos/'),
        ),
    ]
