# Generated by Django 5.1.6 on 2025-03-02 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0003_alter_business_photo_alter_event_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='saved_products',
            field=models.ManyToManyField(blank=True, null=True, related_name='saved_by_users', to='CRUD.product'),
        ),
    ]
