# Generated by Django 5.1.6 on 2025-04-04 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0005_negocio_usuarionormal_remove_event_businesses_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='like',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='like',
            name='usuario',
        ),
        migrations.RenameField(
            model_name='negocio',
            old_name='nombre_negocio',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='usuarionormal',
            old_name='username',
            new_name='nombre_usuario',
        ),
        migrations.RemoveField(
            model_name='negocio',
            name='fecha_creado',
        ),
        migrations.RemoveField(
            model_name='negocio',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='usuarionormal',
            name='fecha_creado',
        ),
        migrations.AddField(
            model_name='comentario',
            name='calificacion',
            field=models.PositiveIntegerField(choices=[(1, '1 estrellas'), (2, '2 estrellas'), (3, '3 estrellas'), (4, '4 estrellas'), (5, '5 estrellas')], default=5),
        ),
        migrations.AddField(
            model_name='negocio',
            name='foto_perfil',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='negocio',
            name='nombre_usuario',
            field=models.CharField(default='No data', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='negocio',
            name='productos_favoritos',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='usuarionormal',
            name='foto_perfil',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuarionormal',
            name='nombre',
            field=models.CharField(default='No data', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuarionormal',
            name='productos_favoritos',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='direccion',
            field=models.CharField(max_length=455),
        ),
        migrations.DeleteModel(
            name='Favorito',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
