# Generated by Django 5.1.6 on 2025-04-04 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0007_alter_negocio_direccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='negocio',
            name='email',
        ),
        migrations.RemoveField(
            model_name='usuarionormal',
            name='email',
        ),
    ]
