# Generated by Django 5.1.6 on 2025-04-04 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0008_remove_negocio_email_remove_usuarionormal_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='tipo_usuario',
            field=models.CharField(default='negocio', max_length=50),
        ),
        migrations.AddField(
            model_name='usuarionormal',
            name='tipo_usuario',
            field=models.CharField(default='normal', max_length=50),
        ),
    ]
