# Generated by Django 5.1.6 on 2025-04-04 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0009_negocio_tipo_usuario_usuarionormal_tipo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negocio',
            name='tipo_usuario',
            field=models.CharField(default='negocio', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='usuarionormal',
            name='tipo_usuario',
            field=models.CharField(default='normal', editable=False, max_length=50),
        ),
    ]
