# Generated by Django 5.1.6 on 2025-04-05 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0011_calificacion_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='calificacion',
            field=models.IntegerField(choices=[(1, '1 estrellas'), (2, '2 estrellas'), (3, '3 estrellas'), (4, '4 estrellas'), (5, '5 estrellas')], default=0),
        ),
    ]
