# Generated by Django 5.1.6 on 2025-04-06 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0012_alter_calificacion_calificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
