# Generated by Django 5.1.6 on 2025-04-23 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0013_producto_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='imagen_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='foto_perfil',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='usuarionormal',
            name='foto_perfil',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
