# Generated by Django 5.1.6 on 2025-04-23 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0014_categoria_imagen_url_alter_negocio_foto_perfil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='descripcion',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
