# Generated by Django 5.1.6 on 2025-04-27 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0015_negocio_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
