# Generated by Django 5.1.6 on 2025-05-03 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0016_negocio_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='negocio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CRUD.negocio'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CRUD.usuarionormal'),
        ),
    ]
