# Generated by Django 5.1.6 on 2025-05-03 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0017_comentario_negocio_alter_comentario_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CRUD.usuarionormal'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='negocio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CRUD.negocio'),
        ),
    ]
