# Generated by Django 5.1.6 on 2025-05-04 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0019_respuesta_producto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Respuesta',
        ),
    ]
