# Generated by Django 5.1.6 on 2025-05-04 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0020_delete_respuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='esRespuesta',
            field=models.BooleanField(default=False),
        ),
    ]
