# Generated by Django 5.1.6 on 2025-05-04 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0021_comentario_esrespuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='comentario_respuesta',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='calificacion',
            field=models.PositiveIntegerField(blank=True, choices=[(1, '1 estrellas'), (2, '2 estrellas'), (3, '3 estrellas'), (4, '4 estrellas'), (5, '5 estrellas')], default=5, null=True),
        ),
    ]
